// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOY5cLKpr1rcX6YRPgZRyMKq0ORBSjiqE',
    appId: '1:1091508024587:web:9950c7ecda57e34bca9e0e',
    messagingSenderId: '1091508024587',
    projectId: 'kira-2c3e4',
    authDomain: 'kira-2c3e4.firebaseapp.com',
    storageBucket: 'kira-2c3e4.firebasestorage.app',
    measurementId: 'G-KSPFFXHGW4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsma2UsiTA-HW8ckHidW1VY0idjxXUxo8',
    appId: '1:1091508024587:android:38a87b582aa8c4c6ca9e0e',
    messagingSenderId: '1091508024587',
    projectId: 'kira-2c3e4',
    storageBucket: 'kira-2c3e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbsjbiBhOsTaoWQWoSOz6xhP4mYrJF9Ho',
    appId: '1:1091508024587:ios:2b4c5cd5bb396822ca9e0e',
    messagingSenderId: '1091508024587',
    projectId: 'kira-2c3e4',
    storageBucket: 'kira-2c3e4.firebasestorage.app',
    iosBundleId: 'com.example.kiraVersionOne',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbsjbiBhOsTaoWQWoSOz6xhP4mYrJF9Ho',
    appId: '1:1091508024587:ios:2b4c5cd5bb396822ca9e0e',
    messagingSenderId: '1091508024587',
    projectId: 'kira-2c3e4',
    storageBucket: 'kira-2c3e4.firebasestorage.app',
    iosBundleId: 'com.example.kiraVersionOne',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOY5cLKpr1rcX6YRPgZRyMKq0ORBSjiqE',
    appId: '1:1091508024587:web:162cbb783586370aca9e0e',
    messagingSenderId: '1091508024587',
    projectId: 'kira-2c3e4',
    authDomain: 'kira-2c3e4.firebaseapp.com',
    storageBucket: 'kira-2c3e4.firebasestorage.app',
    measurementId: 'G-ETMZ1LEFRZ',
  );
}
